/*
 * This source file was generated by the Gradle 'init' task
 */
package com.anton;

import org.junit.Test;

public class MainTest {
  @Test
  public void appHasAGreeting() {
    System.out.println("No test for now");
  }
}
