/*
 * This source file was generated by the Gradle 'init' task
 */
package org.anton;

import org.junit.Test;
import static org.junit.Assert.*;

public class AntonTest {
    @Test public void appHasAGreeting() {
        Anton classUnderTest = new Anton();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
